version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: streetgpt-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - appnet
    # Uncomment to expose MongoDB externally (not recommended for prod)
    ports:
      - "27017:27017"

  app:
    build: .
    container_name: streetgpt-app
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - APP_NAME=${APP_NAME}
      - PASSWORD=${PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=${MONGO_DB_NAME}
    volumes:
      - ./config:/app/config:ro
    networks:
      - appnet

volumes:
  mongo_data:

networks:
  appnet:
    driver: bridge
