OPENAI_API_KEY = "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"

AZURE_API_BASE = "https://streetgpt.openai.azure.com/"
AZURE_API_VERSION = "2023-07-01-preview"
AZURE_API_KEY = "c28a0f3d11eb495f80917114a133d26d"
AZURE_DEPLOYMENT_NAME = "StreetGPT"	

GSHEET_ID = "10XQ8bSlxxEpf9RVt2sDlIsUvha21D-xydEJ33h65Vgo"

PASSWORD = ["regenbogensicher!", "Pilot1-10XQ8bSl"]